---
name: Provision Roles
on:
  workflow_dispatch:
    inputs:
      role_deployment_account_id:
        description: Account no
        required: true
        type: string
      lpa_output_file_role_change:
        description: value change in ouput
        required: true
        type: string
      lpa_organization_ou:
        description: value change in OU
        required: true
        type: string
jobs:
  provision-roles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: ap-south-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Env call
        id: set env
        env:
          TF_VAR_1: ${{ github.event.inputs.role_deployment_account_id }}
         # TF_VAR_2: ${{ github.event.inputs.lpa_output_file_role_change }}
         # TF_VAR_3: ${{ github.event.inputs.lpa_organization_ou }}
      - name: Terraform Apply
        id: apply
        run: |
          cd tf-example/
          terraform init
          terraform validate
          terraform plan 
          terraform apply -auto-approve
